name: Build
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build

      - name: Auto Merge Dependabot PRs
        run: |
          if [[ "${{ github.actor }}" == 'dependabot[bot]' || "${{ github.actor }}" == 'dependabot-preview[bot]' ]]; then
            gh pr merge "${{ github.event.pull_request.number }}" --auto --squash
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
